[service "hostname"]
command = /bin/hostname godel
type = oneshot
restart = never

[service "console"]
command = /sbin/agetty --autologin root --login-program /bin/sh 115200 ttyS0 linux
after = hostname
restart = always
restart_delay = 1s

[service "application"]
command = /usr/local/bin/application --foreground
after = hostname
env = APP_MODE=production APP_PORT=8080
notification-fd = 3
restart = on-failure
restart_limit = 5
restart_delay = 1s

[service "application-ready"]
command = /usr/local/bin/application-check
type = oneshot
restart = never
after = application
